import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Cpu, Code, Wand2 } from "lucide-react";

export default function LandingPage() {
  return (
    <section className="">
      <div className="max-w-7xl mx-auto px-6 py-24">
        
        {/* Hero Section */}
        <div className="text-center">
          <h1 className="text-5xl sm:text-6xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-blue-500">
            AI Tech-Debt Eliminator
          </h1>

          <p className="mt-6 text-lg text-gray-300 max-w-2xl mx-auto">
            Upload your codebase → Detect tech debt → Auto-fix → Improve code quality.
            Powered by advanced AI trained on real-world engineering patterns.
          </p>

          <div className="mt-10 flex justify-center gap-4">
            <Link
              to="/upload"
              className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 transition shadow-lg flex items-center gap-2"
            >
              Get <ArrowRight size={18} />
            </Link>

            <Link
              to="/login"
              className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/20 transition"
            >
              Login
            </Link>
          </div>
        </div>

        {/* Features Section */}
        <div className="mt-28 grid md:grid-cols-3 gap-10">
          <FeatureCard
            icon={<Cpu size={32} />}
            title="AI-Powered Detection"
            description="Deep code analysis to identify hidden maintainability issues."
          />

          <FeatureCard
            icon={<Wand2 size={32} />}
            title="Auto-Fix Suggestions"
            description="Instant refactoring suggestions and improvements generated by AI."
          />

          <FeatureCard
            icon={<Code size={32} />}
            title="Explain The Fix"
            description="Understand every change with clean, readable explanations."
          />
        </div>
      </div>
    </section>
  );
}

function FeatureCard({ icon, title, description }) {
  return (
    <div className="bg-white/5 backdrop-blur-md p-6 rounded-2xl border border-white/10 hover:bg-white/10 transition">
      <div className="mb-4 text-indigo-400">{icon}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-300 text-sm">{description}</p>
    </div>
  );
}
